name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: testdir contains
        run: ls /home/runner/work/dir2db/dir2db/tests/testdir

      - name: Install composer dependencies
        run: composer install --no-scripts

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/